# conda env create --file environment.yml
# mamba env create --file environment.yml
name: challenge_meli
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - python=3.9
  - seaborn
  - fastapi
  - scikit-learn
  - xgboost
  - imbalanced-learn
  - lime
